services:

  dns:
    image: roguesentinels/dns:${RS_DNS_VERSION}
    dns:
      - 192.168.30.50
    networks:
      production:
        ipv4_address: 192.168.30.50
  web2000:
    image: roguesentinels/web2000:${RS_WEB2000_VERSION}
    dns:
      - 192.168.30.50
    networks:
      production:
        ipv4_address: 192.168.30.2

  salmon:
    image: roguesentinels/salmon:${RS_SALMON_VERSION}
    dns:
      - 192.168.30.50
    networks:
      production:
        ipv4_address: 192.168.30.3

  geoserver:
    image: roguesentinels/geoserver:${RS_GEOSERVER_VERSION}
    dns:
      - 192.168.30.50
    networks:
      production:
        ipv4_address: 192.168.30.4

networks:
  production:
    ipam:
      config:
        - subnet: 192.168.30.0/24
          gateway: 192.168.30.1
